# Generated by Django 4.2.30 on 2026-08-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='cargas/%Y/%m/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('con_errores', 'Con errores')], default='pendiente', max_length=20)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('registros_validos', models.PositiveIntegerField(default=0)),
                ('registros_con_error', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Carga de Archivo',
                'verbose_name_plural': 'Cargas de Archivos',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaAuditada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nit', models.CharField(blank=True, max_length=30, verbose_name='NIT')),
            ],
            options={
                'verbose_name': 'Empresa Auditada',
                'verbose_name_plural': 'Empresas Auditadas',
            },
        ),
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Gestión',
                'verbose_name_plural': 'Gestiones',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ErrorValidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='registros.cargaarchivo')),
            ],
            options={
                'verbose_name': 'Error de Validación',
                'verbose_name_plural': 'Errores de Validación',
                'ordering': ['carga', 'fila'],
            },
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='registros.empresaauditada'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='registros.gestion'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_comprobante', models.CharField(blank=True, max_length=50)),
                ('glosa', models.CharField(blank=True, max_length=300)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fila_origen', models.PositiveIntegerField(help_text='Número de fila en el archivo original, para trazabilidad.')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='registros.cargaarchivo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='registros.cuentacontable')),
            ],
            options={
                'verbose_name': 'Registro Contable',
                'verbose_name_plural': 'Registros Contables',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha'], name='registros_r_fecha_cb85d1_idx'), models.Index(fields=['cuenta'], name='registros_r_cuenta__8e0660_idx')],
            },
        ),
    ]
