# Generated by Django 4.2.30 on 2026-08-27 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaauditada',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa Auditada', 'verbose_name_plural': 'Empresas Auditadas'},
        ),
        migrations.AddField(
            model_name='empresaauditada',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del contacto'),
        ),
        migrations.AddField(
            model_name='empresaauditada',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del contacto'),
        ),
        migrations.AddField(
            model_name='empresaauditada',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=30, verbose_name='Teléfono del contacto'),
        ),
        migrations.AddField(
            model_name='empresaauditada',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresaauditada',
            name='rubro',
            field=models.CharField(blank=True, help_text='Ayuda a interpretar mejor los resultados del análisis, ya que el comportamiento contable normal varía según el rubro.', max_length=150, verbose_name='Rubro / sector económico'),
        ),
    ]
