# Generated by Django 4.2.30 on 2026-09-01 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0002_alter_empresaauditada_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(help_text='Nombre del modelo afectado, ej. EmpresaAuditada.', max_length=100)),
                ('objeto_id', models.PositiveIntegerField()),
                ('objeto_descripcion', models.CharField(blank=True, help_text='Representación legible del objeto al momento del cambio.', max_length=200)),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('edicion', 'Edición')], max_length=20)),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
    ]
