# Generated by Django 4.2.30 on 2026-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_historialcambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorvalidacion',
            name='tipo',
            field=models.CharField(choices=[('error', 'Error'), ('aviso', 'Aviso')], default='error', max_length=10),
        ),
    ]
