# Generated by Django 4.2.30 on 2026-09-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_gestion_anio_no_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaarchivo',
            name='estado',
            field=models.CharField(
                choices=[
                    ('pendiente', 'Pendiente'),
                    ('validado', 'Validado'),
                    ('con_observaciones', 'Cargado con pendientes'),
                    ('con_errores', 'Con errores'),
                ],
                default='pendiente',
                max_length=20,
            ),
        ),
    ]
