# Generated by Django 4.2.30 on 2026-09-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_cargaarchivo_estado_con_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaarchivo',
            name='formato_detectado',
            field=models.CharField(
                blank=True,
                choices=[
                    ('diario_pdf', 'Libro Diario (PDF)'),
                    ('diario_plano', 'Libro Diario (Excel/CSV)'),
                    ('mayor', 'Libro Mayor (Excel/CSV)'),
                ],
                max_length=20,
                verbose_name='Tipo de libro detectado',
            ),
        ),
    ]
