# Generated by Django 4.2.30 on 2026-09-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0008_cargaarchivo_formato_detectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaauditada',
            name='categoria_cierre',
            field=models.CharField(
                choices=[
                    ('general', 'Comercio, servicios, bancos y seguros — cierra 31 de diciembre'),
                    ('industrial', 'Industrial o petrolera — cierra 31 de marzo'),
                    ('agropecuaria', 'Agropecuaria o agroindustrial — cierra 30 de junio'),
                    ('minera', 'Minera — cierra 30 de septiembre'),
                ],
                default='general',
                help_text=(
                    'Define en qué mes cierra el año fiscal de esta empresa. Se usa solo '
                    'para sugerir las fechas al crear una nueva gestión — siempre se pueden '
                    'ajustar a mano si hay una excepción real.'
                ),
                max_length=20,
                verbose_name='Categoría de cierre de gestión (SIN)',
            ),
        ),
    ]
