# Generated by Django 4.2.30 on 2026-09-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0009_empresaauditada_categoria_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaarchivo',
            name='registros_con_aviso',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='revisado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cargas_revisadas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
