# Generated by Django 4.2.30 on 2026-09-14 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0010_cargaarchivo_confirmacion_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargaarchivo',
            name='estado',
            field=models.CharField(
                choices=[
                    ('pendiente', 'Pendiente'),
                    ('validado', 'Validado'),
                    ('con_observaciones', 'Cargado con pendientes'),
                    ('con_errores', 'Con errores'),
                    ('anulada', 'Anulada'),
                ],
                default='pendiente',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='motivo_anulacion',
            field=models.TextField(blank=True, verbose_name='Motivo de la anulación'),
        ),
        migrations.AddField(
            model_name='cargaarchivo',
            name='anulado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='cargas_anuladas',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
