# Generated by Django 4.2.30 on 2026-09-22 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registros', '0011_cargaarchivo_anulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorvalidacion',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorvalidacion',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorvalidacion',
            name='revisado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='avisos_revisados',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
