# Generated by Django 4.2.30 on 2026-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_errorvalidacion_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorvalidacion',
            name='comentario_revision',
            field=models.TextField(blank=True),
        ),
    ]
