# Generated by Django 4.2.30 on 2026-09-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_errorvalidacion_comentario_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocontable',
            name='saldo',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                help_text=(
                    "Saldo tal como venía en el archivo original (columna 'Saldo' del "
                    "Libro Mayor), guardado como referencia. No se calcula ni se "
                    "valida — el sistema no conoce la naturaleza deudora/acreedora "
                    "de cada cuenta, así que no intenta recalcularlo."
                ),
            ),
        ),
    ]
